SELECT DEPARTAMENTO.NOME AS Departamento, 
	PESSOA.NOME AS Pessoa, 
	PESSOA.SALARIO AS Salario
FROM DEPARTAMENTO (NOLOCK)
INNER JOIN PESSOA (NOLOCK)
   ON DEPARTAMENTO.ID = PESSOA.DEPTID
WHERE PESSOA.SALARIO = (SELECT MAX(SALARIO) FROM PESSOA WHERE DEPTID = DEPARTAMENTO.ID);