CREATE TABLE DEPARTAMENTO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE PESSOA (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL,
    DEPTID INT,
    FOREIGN KEY (DEPTID) REFERENCES DEPARTAMENTO(ID)
);